<?php

return [
    //Main titles of the articles
    'welcome' => 'Welcome to our application!',
    'aboutShip' => 'About the ship',
    'makingOfTheVessel' => 'Making of the Vessel',
    'damen' => 'Damen',
    'captain' => 'Captain AI',
    'tech' => 'The Technology',

    //Subtitles of the articles
    'aboutShip-sub' => 'Use our website to discover the possibilities of autonomous Shipping!',
    'makingOfTheVessel-sub' => 'The vessel has been in the making for quite a while, but is not finished yet',
    'damen-sub' => 'Damen is a family owned business that stands for fellowship, craftsmanship, entrepreneurship and stewardship.',
    'captain-sub' => 'The brains of the vessel have been engineered by one of the most advanced companies in the field of autonomous
                        shipping: Captain AI.',
    'neuralNetwork' => 'Neural Network',
    'cloud' => 'Cloud',
    'sensor' => 'Sensors',

    //Paragraphs which contain the content of the articles
    'aboutShip-par' => 'Our team created a website where you can explore autonomous shipping in
                                an entertaining way. Together with Damen and Captain AI, we created a
                                detailed experience where you can learn about autonomous sailing and its
                                future, see what some of the autonomous ships look like and play a game to
                                learn about autonomous vessels.',

    'makingOfTheVessel-par' => 'The vessels future is looking brighter than ever with the help of Damen to change the
                                vessel from using petrol to being fully electric while also installing all the necessary
                                equipment to make it autonomous.',

    'damen-par' => '"We believe that our oceans, seas, lakes and rivers offer humanity a growing range
                         of possibilities in terms of trade, food, energy and recreation. We provide maritime
                         solutions to meet these opportunities, through design, shipbuilding, ship repair and
                         related services."',

    'captain-par' => 'Captain AI are based in Rotterdam, Netherlands. They provide all of the needed
                            technology to make the boat think for itself, while also making it as safe as
                            possible for the passengers. In this particular field of techonology, Captain AI is one of the most
                            advanced and innovative companies in the world.',

    'neuralNetwork-par' => 'CaptainAI are building a pipeline for fully automatic data collection and
                            labeling. They do this in order to create dependable predictions of the
                            behavior of vessels and other factors. The latest AI models are being used
                            for object detection, image classification and instance segmentation to
                            create comprehensive situational awareness.',

    'cloud-par' => 'For data visualization of 3D scenes, plots and sensor data dat CaptainAI
                            have built Atlantis, their scalable cloud infrastructure solution. For
                            the route planner a optimal and real time paths is generated by
                            processing terabytes of data in the cloud.',

    'sensor-par' => 'Our vessels use a variety of inputs for our sensor fusion algorithm,
                           in order to create a reliable view of every situation. It make use
                           of radar, cameras, GPS, Octance, sonar and AIS already installed on
                           most vessels.',
];
