name: Deploy to heroku

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Deployment:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2
          
    - name: Deploy to Heroku
      uses: AkhileshNS/heroku-deploy@v3.12.12
      with:
          heroku_api_key: 6828e0c0-4e74-4411-a411-52d96c29a8fa
          heroku_email: hwid0001@hz.nl
          heroku_app_name: autonomous-transport
          run: git push heroku main
   
